name: Build Docker Container & Push to DO Registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_django_job:
    uses: SandorNicuAlin/django-k8s/.github/workflows/test-django.yaml@master
  django_build:
    runs-on: ubuntu-latest
    needs: [test_django_job]
    env:
      DJANGO_SECRET_KEY: test-key-not-good-maybe-make-one-better
    
    steps:
    - uses: actions/checkout@v2